### ISSUE TITLE
error starting server.js

### ISSUE THREAD

**Issue by michaelpalumbo** [worldmaking/manifolds#6]
Hi @MissCrispenCakes running server.js in a branch from boilerplate yields:

```shell
node server.js
internal/fs/utils.js:220
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'server-key.pem'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at Object.<anonymous> (/Users/mp/manifolds/server.js:12:11)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'server-key.pem'
}
```

**Comment by michaelpalumbo** [comment]
hmm, makes sense not to commit the security creds, haha, but having not worked with this before how should I generate my own keys?

**Comment by MissCrispenCakes** [comment]
yes - I mentioned that you need the keys and that I would set it up at york when I came to the lab today

S

**Comment by MissCrispenCakes** [comment]
@michaelpalumbo are you in between 1430h-1630h ? I'll be in then to test it and I'm bringing the keys with me to install locally. Do we have a local shared folder or should I use Pac-Man ?

**Comment by michaelpalumbo** [comment]
@MissCrispenCakes would a dropbox folder work? I can't be there at that time today. how about Thursday anytime between 9-11am?
